## https://taplo.tamasfe.dev/configuration/file.html

include = ["**/*.toml"]

exclude = [".idea/**", ".venv/**", "target/**"]

[formatting]
array_auto_collapse = false
indent_string = '    '
reorder_keys = false
allowed_blank_lines = 1

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "build-dependencies",
    "dependencies",
    "dev-dependencies",
    "workspace.dependencies",
    "target.*.dependencies",
]

[rule.formatting]
reorder_arrays = true
reorder_keys = true
