use std::fs;

use anyhow::Context;

use crate::prelude::*;
use crate::utils::tips;

/// Remove artifacts generated by shinc.
#[derive(clap::Parser, Debug)]
pub struct CleanCmd {}

impl CliCommand for CleanCmd {
    fn run(&self) -> CliResult {
        tips::debug("Cleaning artifacts");

        let target_dir = CONFIG.target_dir();
        if target_dir.is_dir() {
            fs::remove_dir_all(&target_dir).with_context(|| {
                format!("failed to remove target directory '{}'", target_dir.display())
            })?;
        }

        Ok(())
    }
}
