name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: "Upload release binaries"
    needs: create-release
    strategy:
      matrix:
        include:
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          # macOS
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: shinc
          checksum: sha256
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # bump-homebrew-formula:
  #   needs: upload-assets
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update Homebrew formula
  #       uses: dawidd6/action-homebrew-bump-formula@v4
  #       with:
  #         token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
  #         no_fork: true
  #         tap: druagoon/homebrew-brew
  #         formula: shinc
  #         user_name: github-actions[bot]
  #         user_email: 41898282+github-actions[bot]@users.noreply.github.com
